-- Active: 1746345983123@@127.0.0.1@5435@clients
CREATE TABLE IF NOT EXISTS clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ip_address TEXT UNIQUE NOT NULL,
    capacity INT NOT NULL,
    rate_per_second INT NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO clients 
        (ip_address, capacity, rate_per_second) 
    VALUES 
        ('127.0.0.1', 100, 10)
    ON CONFLICT (ip_address) DO NOTHING;

