-- Active: 1746345983123@@127.0.0.1@5435@clients
CREATE TABLE IF NOT EXISTS clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ip_address TEXT UNIQUE NOT NULL,
    name TEXT,
    capacity INT NOT NULL,
    rate_per_second INT NOT NULL,
    PRIMARY KEY (id)
);
