env: local # local || prod

proxy: 
  host: localhost
  port: 8080
  read_timeout: 30s
  write_timeout: 45s
  idle_timeout: 90s
  health_check:
    interval: 30s
    workers_count: 10

backends:
  - http://localhost:8100
  - http://localhost:8101
  - http://localhost:8102
  - http://localhost:8103
  - http://localhost:8104
  - http://localhost:8105
  - http://localhost:8106
  - http://localhost:8107
  - http://localhost:8108
  - http://localhost:8109

postgresql:
  host: localhost
  port: 5435
  username: postgres
  password: postgres
  db: clients
  connection:
    attemprs: 5
    delay: 5s